resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astropy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    envs:
    # Code style
    - linux: codestyle
    # Standard tests
    - linux: py36-test
    - linux: py37-test
    - linux: py38-test
    - macos: py36-test
    - macos: py37-test
    - macos: py38-test
    - windows: py36-test
    - windows: py37-test
    - windows: py38-test
